# August 28, 2020

projectName: EsblStrains
dataDir: /science/ansintsova/esbl_strains/raw
outDir:  /science/ansintsova/esbl_strains/
sampleFile: /nfs/home/ansintsova/esbl_strains/samples.txt

#Preprocessing
mink: 11
trimq: 14
mapq: 20
minlen: 45

merged: false # By default to do not use merge for isolate genome assembly


# Align to reference
reference: LL6 # or path to genome assembly
scaffold: #min0, min500 if want to use filtered assembly

#
tmpdir: /science/ansintsova/esbl_strains/tmp
ram: 4


# panX
gbkFolder:
panXpath: /nfs/home/ansintsova/pan-genome-analysis

# Standard parameters. Dont change these!!!
adapters: '/nfs/cds-shini.ethz.ch/exports/biol_micro_cds_gr_sunagawa/SequenceStorage/resources/adapters.fa'
phix: '/nfs/cds-shini.ethz.ch/exports/biol_micro_cds_gr_sunagawa/SequenceStorage/resources/phix174_ill.ref.fa.gz'
bbmap_human_ref: '/nfs/cds-shini.ethz.ch/exports/biol_micro_cds_gr_sunagawa/SequenceStorage/resources/human_bbmap_ref/'
bbmap_mouse_ref: '/nfs/cds-shini.ethz.ch/exports/biol_micro_cds_gr_sunagawa/SequenceStorage/resources/mouse_bbmap_ref/'